baseURL: "https://stevenhoward.net"
languageCode: "en-us"
title: "Steven Howard - DevOps & Cloud Engineer"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: manni

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #- identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Steven Howard - DevOps & Cloud Engineer"
  description: "Automation is my Passion. The Cloud is my Canvas."
  staticPath: "" # The path to serve the static files from
  favicon: "/images/home/SH.png"
  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    #   textColor:
    #   secondaryTextColor:
    #   backgroundColor:
    #   secondaryBackgroundColor:
    primaryColor: "#008CFF"
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: " " # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Steven Howard."
    subtitle: "Automation is my Passion."
    content: "The Cloud is my Canvas."
    image: /images/home/profile.jpg
    bottomImage:
      enable: true
      roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/resume/"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/sp-howard
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/sp-howard/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/home/profile.jpg
    content: |-
      **Hi! I'm Steven**, a lifelong technology enthusiast and an IT professional of 7 years. I thrive on new challenges. Wrapping my head around a complex problem, researching solutions, generating a proof of concept, implementing, testing, and documenting - Each step reinforces my conviction that any challenge can be overcome with willpower, determination... or quick walk around the block. 

      I initially ventured into the tech world as an aspiring Web Developer. I dove headlong into the deep waters of software development, and I **fell in love**. The blend of logic and creativity that coding allows suited me perfectly. 

      My coding ambitions would have to be put on hold, as the opportunities in my surroundings were sparse. I instead found myself in the world of IT Support, and what an invaluable detour it's been. My first few years were spent in the Managed Service Provider space, where my growth was exponential. Every day I was presented with a problem I'd never encountered. A piece of software I'd never used. An error I'd never seen. No matter what was broken, ***I made it work again.*** I found that IT fulfilled the same craving for complexity and problem-solving that I had first found in coding. I further honed my skills in Windows Server Administration and Cisco Networking, quickly becoming an essential contributor on any team.

      Now, I'm ready to enter a new arena: Cloud Computing. I'm captivated at the possibilities this technology provides. I've spent many months drinking from the firehouse that is AWS, DevOps, and Infrastructure as Code. I encourage you to take a look at my projects, particularly my **Cloud Portfolio** blog post.

      As you navigate through my portfolio, you'll discover a professional who is continuously evolving, always eager to learn, and unyielding in the face of challenges—let's conquer the cloud together.
    skills:
      enable: false
      title: "A glimpse at my non-technical side:"
      items:
        - "Gaming"
        - "Sci-Fi"
        - "Reddit"
        - "Woodworking"
        - "Painting"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Network Administrator"
        company: "Family Healthcare Network"
        companyUrl: "https://www.fhcn.org/"
        date: "June 2021 - Present"
        years: "2+"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          <div class="experience-content">

          - **Application Deployment & Automation** – Led a comprehensive revamp of application deployment and patch management across 50 clinical sites, affecting over 3,000 endpoints. Utilized PDQ to automate the overnight updates for mission-critical Electronic Health Record (EHR) software, eliminating the need for manual intervention and saving the organization 20 hours of overtime monthly, equivalent to $14,400 in cost savings each year.
          - **Cloud & Collaboration Services** – Served as the go-to Subject Matter Expert for Microsoft 365 services utilized by 1500+ users. Oversaw Azure Active Directory administration and lifecycle management of all Microsoft 365 applications. Orchestrated a seamless migration from on-premises Microsoft Exchange to Exchange Online with zero data loss. Crafted the organization's Intranet and Business Intelligence dashboard in SharePoint. Implemented security policies through Purview/Defender, including Data Loss Prevention (DLP) and Conditional Access.
          - **Network Reliability & Automation** – Developed custom Python scripts to automate the configuration and auditing of network switches, increasing security by identifying and mitigating unauthenticated switchports. Acted as the first-line responder for network outages and VPN connectivity. Spearheaded the configuration and deployment of Cisco hardware, upgrading end-of-life equipment and enabling the successful launch of 10+ new clinical sites. Diligently maintained up-to-date network diagrams and documentation.
          - **AWS Administration** – Managed and secured Linux EC2 instances for the organization's public websites, implementing an automated solution to resolve availability issues by restarting instances upon health check failures. Upheld the principle of least privilege while granting third-party developers secure access to accounts.
          - **Virtual Infrastructure & System Administration** – Oversaw the daily administration and optimization of 100+ Windows servers (2012, 2016, 2019) in VMware's vCenter. Orchestrated the migration of mission-critical services, while routinely managing DHCP scopes, DNS configurations, and GPOs. 

          </div>
      - job: "Network Administrator"
        company: "Valley Republic Bank"
        companyUrl: "https://www.tcbk.com/"
        date: "May 2019 – May 2021"
        years: "2"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          # content: I worked as a software developer for more than one year in Amazon.
        content: |
          <div class="experience-content">

          - **Enterprise Security** – Spearheaded security enhancements across 25 servers and 150 workstations, achieving a 95% reduction in vulnerability score as reported by Rapid7's InsightVM. Utilized WSUS and PowerShell scripting for targeted vulnerability remediation and implemented port-security on network switches. These strategic initiatives led to superior performance in federal audits, including FFIEC, PCI, GLBA, SOX, and BSA compliance. 
          - **Technical Documentation** – Developed and curated a team knowledge base in Confluence, contributing over 50 articles on topics ranging from network infrastructure and application error resolution to end-user training guides, thereby enhancing team efficiency and problem-solving capabilities.

          </div>
      - job: "Technology Consultant"
        company: "Managed Service Providers"
        years: "2.5"
        companyUrl: "https://www.diamondit.pro/"
        date: "January 2017 – April 2019"
        info:
          enable: true
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          <div class="experience-content">

          - **Network Implementation & Configuration** – Engineered and fully deployed over 20 networks across various scales, from SOHO to Enterprise-grade with up to 500 endpoints. Oversaw the complete lifecycle from initial proposal to implementation, configuring switches, routers, and firewalls to meet customized requirements.
          - **End-User Support** – Provided both in-field and remote support for hardware, software, and network issues to medium-sized businesses and local governments. Consistently earned an average customer survey score of 9.75/10 for service excellence, while resolving over 200 tickets monthly.

          </div>
      - job: "Freelance"
        company: "Web Developer"
        years: "5"
        companyUrl: "https://stevenhoward.net/"
        date: "March 2016 – May 2021"
        info:
          enable: true
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          <div class="experience-content">

          - **Custom Website Development & Client Relations** – Developed, designed, and deployed websites using WordPress for clientele in the real estate and retail sectors. Managed end-to-end web solutions, from domain configuration and hosting to email migration. Actively maintained websites by updating CMS, plugins, and providing on-call support, ensuring optimal performance and user experience. 
          - **Project Example** – Created a fully responsive real estate website with MLS (multiple listing service) integration (http://landrealty.biz), which led to a 1000% increase in online inquiries for the client.
          </div>

  # Projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Cloud Portfolio
        content: Static portfolio website hosted on AWS S3, with serverless components including API Gateway, Lambda, and DynamoDB. Also utilized Route53, Amazon Certificate Manager, and CloudFront. Infrastructure was converted to IaC using Terraform, and implemented via CI/CD pipeline using GitHub Actions with Cypress end-to-end testing.
        image: /images/blog/cloud-resume/cloud-resume-diagram.png
        featured:
          name: Blog Post
          link: /blogs/cloud-portfolio/
        badges:
          - "AWS"
          - "Terraform"
          - "GitHub Actions"
          - "Python"
          - "Javascript"
          - "HTML/CSS"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/sp-howard/cloud-resume-back-end
          #- icon: fab fa-twitter
          #w  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

  # Achievements / Certifications
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: AWS Solutions Architect Associate
        content: |
          June 2023 <br>
          2GT0MQ420BV11JWT
        url: https://aws.amazon.com/verification
        image: images/home/certs/aws-certified-solutions-architect-associate.png
      - title: Hashicorp Terraform Associate
        content: July 2023 <br>
        url: https://example.com
        image: images/home/certs/terraform.png
      - title: Cisco Certified Network Associate (CCNA)
        content: |-
          February 2020 <br>
          NYQDNWFPKDEQ16WG
        url: https://cp.certmetrics.com/cisco/en/public/verify/credential/NYQDNWFPKDEQ16WG
        image: images/home/certs/ccna.png
      - title: AWS Cloud Practitioner
        content: |-
          March 2022 <br>
          K6H5CCR2QNRQ1LKC
        url: https://aws.amazon.com/verification
        image: images/home/certs/aws-certified-cloud-practitioner.png
      - title: CompTIA Project+
        content: |
          October 2021 <br>
          89MWG7XQF14Q18S3
        url: https://www.certmetrics.com/comptia/public/verification.aspx?code=89MWG7XQF14Q18S3
        image: images/home/certs/comptia-project-certification.1.png
      - title: CompTIA Security+
        content: |
          September 2020 <br>
          EP71PTLPQPEQ16WQ
        url: https://www.certmetrics.com/comptia/public/verification.aspx?code=EP71PTLPQPEQ16WQ
        image: images/home/certs/comptia-security-ce-certification.png
      - title: CompTIA Network+
        content: |-
          April 2018 <br>
          Y2Q7TQXPPG141MK4
        url: https://www.certmetrics.com/comptia/public/verification.aspx?code=NSF0EHMX68L6FZGM
        image: images/home/certs/comptia-network-ce-certification.1.png
      - title: CompTIA A+
        content: |-
          December 2016 <br>
          NWYHN9P3FCE4YNMM
        url: https://www.certmetrics.com/comptia/public/verification.aspx?code=8CKHZEJGF3EQYE4Z
        image: images/home/certs/comptia-a-ce-certification.1.png

  # Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Embarking on a new adventure? Let's conquer the cloud together!
    email: steven@stevenhoward.net
    btnName: Email Me
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: mpzgzdkg # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"

  # Footer
  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/sp-howard
      linkedin: https://www.linkedin.com/in/sp-howard/
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
