name: "Hugo Build and Copy to S3"

on:
  push:
    branches:
      - main

jobs:
  hugo-terraform:
    name: "Hugo Build and Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3

      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.115.1'

      - name: "Build Site"
        run: |
          cd stevenhoward.net
          hugo --minify

      - name: "Copy website files to S3"
        uses: qoqa/action-s3-cp@v1.1
        env:
          AWS_S3_BUCKET: 'stevenhoward.net'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          AWS_S3_PATH: '/.'
          FILE: 'stevenhoward.net/public -recursive'

      - name: "Cypress End-to-End Test"
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/e2e/stevenhoward.cy.js
